# Generated by Django 2.2.2 on 2019-07-27 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_stream', models.TextField()),
                ('input_type', models.TextField()),
                ('stream_processor', models.TextField()),
                ('remote_address', models.TextField()),
                ('videostream_port', models.IntegerField(default=-1)),
                ('websocket_port', models.IntegerField(default=-1)),
                ('pid', models.IntegerField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
